//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vshope.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vshope.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;table style=&quot;background: #f4f4f4; font-family: arial; font-size: 12px; font-weight: normal; margin: 0; padding: 0; color: #222222 !important;&quot;
        ///       cellspacing=&quot;0&quot;
        ///       cellpadding=&quot;0&quot;
        ///       width=&quot;100%&quot;
        ///       bgcolor=&quot;#fff&quot;&gt;
        ///    &lt;tbody&gt;
        ///    &lt;tr&gt;
        ///        &lt;td width=&quot;5%&quot;&gt;
        ///            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;15&quot;&gt;
        ///                &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td&gt;
        ///                        &lt;div style=&quot;font-size: 0; line-height: 0; min-height: 0;&quot;&gt;&amp;nbsp;&lt;/div&gt;
        ///       [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string UserRegistrationConfirmedEmail {
            get {
                return ResourceManager.GetString("UserRegistrationConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт Vshope успешно активирован.
        /// </summary>
        internal static string UserRegistrationConfirmedSubject {
            get {
                return ResourceManager.GetString("UserRegistrationConfirmedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;table style=&quot;background: #f4f4f4; font-family: arial; font-size: 12px; font-weight: normal; margin: 0; padding: 0; color: #222222 !important;&quot;
        ///       cellspacing=&quot;0&quot;
        ///       cellpadding=&quot;0&quot;
        ///       width=&quot;100%&quot;
        ///       bgcolor=&quot;#fff&quot;&gt;
        ///    &lt;tbody&gt;
        ///    &lt;tr&gt;
        ///        &lt;td width=&quot;5%&quot;&gt;
        ///            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;15&quot;&gt;
        ///                &lt;tbody&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td&gt;
        ///                        &lt;div style=&quot;font-size: 0; line-height: 0; min-height: 0;&quot;&gt;&amp;nbsp;&lt;/div&gt;
        ///       [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string UserRegistrationCreatedEmail {
            get {
                return ResourceManager.GetString("UserRegistrationCreatedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приветствуем в Vshope!.
        /// </summary>
        internal static string UserRegistrationCreatedSubject {
            get {
                return ResourceManager.GetString("UserRegistrationCreatedSubject", resourceCulture);
            }
        }
    }
}
