export const ErrorConsts = {
  VALIDATION_MIN_LENGTH_PASSWORD: 6,
  VALIDATION_MAX_LENGTH_SMALL: 256,
  VALIDATION_MAX_LENGTH_NORMAL: 1024,
  VALIDATION_MAX_LENGTH_BIG: 4096,
  VALIDATION_MAX_VALUE_HUNDRED: 100,
  VALIDATION_MAX_VALUE_SMALL: 1000,
  VALIDATION_MAX_VALUE_SMALLNORMAL: 100000,
  VALIDATION_MAX_VALUE_NORMAL: 10000000000,
  VALIDATION_MIN_LATITUDE: -90,
  VALIDATION_MAX_LATITUDE: 90,
  VALIDATION_MIN_LONGITUDE: -180,
  VALIDATION_MAX_LONGITUDE: 180
}
