export const ExceptionCodes = {
  COMMON_INVALID_ARGUMENTS: 'COMMON_INVALID_ARGUMENTS',
  COMMON_NOT_EXIST: 'COMMON_NOT_EXIST',
  DB_RELATED_ENTITY_EXISTS: 'DB_RELATED_ENTITY_EXISTS',
  DISABLED_FUNCTIONALITY: 'DISABLED_FUNCTIONALITY',
  FILE_IS_TOO_BIG: 'FILE_IS_TOO_BIG',
  READONLY_FIELD: 'READONLY_FIELD',
  FORBIDDEN: 'FORBIDDEN',

  AUTH_JWT_INCORRECT: 'AUTH_JWT_INCORRECT',
  AUTH_CODE_INCORRECT: 'AUTH_CODE_INCORRECT',
  AUTH_REFRESH_TOKEN_INCORRECT: 'AUTH_REFRESH_TOKEN_INCORRECT',

  VK_AUTH_TOKEN_INCORRECT: 'VK_AUTH_TOKEN_INCORRECT',
  VK_ID_INVALID: 'VK_ID_INVALID',

  BL_CODE_USER_ALREADY_EXIST: 'BL_CODE_USER_ALREADY_EXIST',
  BL_CODE_USER_NOT_CONFIRMED: 'BL_CODE_USER_NOT_CONFIRMED'
}
